### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by adidaddy** [hidden-refuge/3proxy#1]
Can you write up a quick guide on how to execute and install?

**Comment by hidden-refuge** [comment]
It is a shell script that you run from your terminal.

Before you run it make sure you have all compilation tools installed. The package "build-essential" should be enough. The package can have different names on different Linux distributions.

1. Download 3proxy-install.sh or 3proxy-install-dev.sh via wget/curl to your server.
2. Give the file execution permission with chmod.
3. Run it.

I will add a small guide to the readme.
